version: '3.5'

services:
  ifr-trt-gpu0:
    image: insightface-rest:${IFR_VERSION}
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile_trt
    hostname: ifr
    env_file:
      - .env
    volumes:
      - ../models:/models
      - ../if_rest:/app/if_rest
      - ../entrypoint.sh:/app/entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:18080/health" ]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 30s

  ifr-trt-gpu1:
    image: insightface-rest:${IFR_VERSION}
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile_trt
    hostname: ifr
    env_file:
      - .env
    volumes:
      - ../models:/models
      - ../if_rest:/app/if_rest
      - ../entrypoint.sh:/app/entrypoint.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:18080/health" ]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 30s


  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx-ifr
    volumes:
      - ../misc/nginx_conf/conf.d:/etc/nginx/conf.d
    ports:
      - 18080:18080
    depends_on:
      - ifr-trt-gpu0
    ulimits:
      nofile:
        soft: 200000
        hard: 200000