services:
  ifr-cpu:
    image: insightface-rest-cpu:${IFR_VERSION}
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile_cpu
    hostname: ifr
    env_file:
      - cpu.env
    volumes:
      - ../models:/models
      - ../if_rest:/app/if_rest
      - ../entrypoint.sh:/app/entrypoint.sh
    ports:
      - 18081:18080

