version: '3.5'

services:
  ifr-trt-gpu0:
    image: insightface-rest:${IFR_VERSION}
    build:
      context: ../src
      dockerfile: ../src/Dockerfile_trt
    hostname: ifr
    env_file:
      - .env
    volumes:
      - ../models:/models
      - ../src:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

  ifr-trt-gpu1:
    image: insightface-rest:${IFR_VERSION}
    build:
      context: ../src
      dockerfile: ../src/Dockerfile_trt
    hostname: ifr
    env_file:
      - .env
    volumes:
      - ../models:/models
      - ../src:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]


  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx-ifr
    volumes:
      - ../misc/nginx_conf/conf.d:/etc/nginx/conf.d
    ports:
      - 18080:18080
    depends_on:
      - ifr-trt-gpu0
    ulimits:
      nofile:
        soft: 200000
        hard: 200000