FROM nvcr.io/nvidia/tensorrt:20.12-py3

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install -y libgl1-mesa-glx protobuf-compiler libprotoc-dev libb64-0d
ENV PIP_INSTALL="python -m pip --no-cache-dir install --upgrade"
RUN $PIP_INSTALL mxnet insightface fastapi uvicorn ujson numba aiofiles
RUN $PIP_INSTALL onnx==1.7.0
RUN $PIP_INSTALL onnx-simplifier
RUN $PIP_INSTALL nvidia-pyindex && pip install tritonclient[http,grpc]

# Workaround for tensorrt:20.12-py3 image, which has broken support for BatchNorm layers
RUN bash /opt/tensorrt/install_opensource.sh -b master
# For some reason symlink libnvonnxparser.so.7 won't update to newly compiled version if old binary exist
RUN rm /usr/lib/x86_64-linux-gnu/libnvonnxparser.so.7.2.2

WORKDIR /app
COPY api_trt /app

ENTRYPOINT [ "bash" ]
CMD ["entrypoint.sh"]
