FROM nvcr.io/nvidia/tensorrt:20.09-py3

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

WORKDIR /app

RUN apt-get update && apt-get install -y libgl1-mesa-glx protobuf-compiler libprotoc-dev libb64-0d
ENV PIP_INSTALL="python -m pip --no-cache-dir install --upgrade"
RUN $PIP_INSTALL mxnet insightface fastapi uvicorn ujson numba
RUN $PIP_INSTALL onnx==1.7.0
RUN $PIP_INSTALL onnx-simplifier
RUN $PIP_INSTALL nvidia-pyindex && pip install tritonclient[http,grpc]

COPY converters /app

ENTRYPOINT ["bash"]

